version: '3'

services:
  scalargis:
    build:
      context: .
    image: ${IMAGE_NAME}
    expose:
      - ${PORT}
    ports:
      - ${HOST_PORT}:${PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker:/var/scalargis/scalargis/configs
      - ./scalargis/instance:/var/scalargis/scalargis/instance
      - ./scalargis/tmp:/var/scalargis/scalargis/tmp
      - ./scalargis/uploads:/var/scalargis/scalargis/uploads
      - ./scalargis/resources:/var/scalargis/scalargis/resources
      - ./scalargis/logs:/var/scalargis/scalargis/logs
      - ./scalargis/app/plugins:/var/scalargis/scalargis/app/plugins
      - ./scalargis/app/static:/var/scalargis/scalargis/app/static
      - ${HOST_DATA_DIR}:/var/scalargis/data
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    command: ["sh", "-c", "python3 /var/scalargis/scalargis/server.py 2>&1"]
    restart: always
    environment:
      - APP_CONFIG_FILE=${APP_CONFIG_FILE}
      - PYTHONPATH=/var/scalargis/scalargis
      - PORT=${PORT}
      - URL_PREFIX=${URL_PREFIX}
    networks:
      - scalargis
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: ${CONTAINER_NAME}-db
    hostname: ${CONTAINER_NAME}-db
    env_file:
      - docker/.env.docker
    volumes:
      - scalargis-db-data:/var/lib/postgresql/data
    ports:
      - 5001:5432
    networks:
      - scalargis
    restart: on-failure
    healthcheck:
      test: "pg_isready -d scalargis -U scalargis"
      interval: 60s
      timeout: 10s
      retries: 4


networks:
  scalargis:

volumes:
  scalargis-db-data:
